#[toml_cfg::toml_config]
pub struct Config {
    #[default("")]
    wifi_ssid: &'static str,
    #[default("")]
    wifi_pass: &'static str,
}

pub fn log_wifi_config() {
    // The constant `CONFIG` is auto-generated by `toml_config`.
    let app_conifg = CONFIG;
    log::info!("Happy Fish has the following credentials:");
    log::info!("\twifi_ssid={}", app_conifg.wifi_ssid);
    log::info!("\twifi_pass={}", app_conifg.wifi_pass);
}